insert into currency_exchange
(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
values (1001,'USD','INR',65,'');

insert into currency_exchange
(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
values (1002,'EUR','INR',75,'');

insert into currency_exchange
(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
values (1003,'AUD','INR',25,'');


